name: 'spring-boot-microservices-course'
services:
  catalog-service:
    image: 41kailasrakh/bookstore-catalog-service
    container_name: catalog-service
    environment:
      - SPRING_PROFILE_ACTIVE=docker
      - DB_URL=jdbc:postgres:/catalog-db:5432/catalog
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8081:8081"
    depends_on:
        catalog-db:
          condition: service_healthy
    restart: unless-stopped
    deploy:
        resources:
          limits:
            memory: 700m
